spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE/
          predicates:
            - Path=/account/**
        - id: weather-provider
          uri: lb://WEATHER-PROVIDER/
          predicates:
            - Path=/weather/**
        - id: user-cities-db-route
          uri: lb://DATABASE-SERVICE/
          predicates:
            - Path=/cities/**
          filters:
            - RewritePath=/cities, /user/cities
  application:
    name: gateway
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true